### PR TITLE
Redux Saga Logging Magic

### PR DESCRIPTION
**Pull request by rmevans9**
Note: This has mostly been tested in my own app but will be setting up to test it in the demo app over the next few days.

I had to have the "end user" pull two internal methods and pass them to Reactotron as I was unable to find a way to pull them within the reactotron code without it throwing errors.

This PR should be considered a WIP

### CODE REVIEW

**Comment by skellock** [comment]
I can't tell you how happy this makes me!  Will check it out this weekend.

**Comment by rmevans9** [comment]
In trying to see if there is a way to not have the error logged the entire way up the saga chain I couldn't find one as each of the sagas threw the error as if the error occurred in their saga. I am thinking we might need to do more filtering based on the fact that if the exact error was thrown already instead of trying to only allow the closest saga to throw it.

**Comment by skellock** [comment]
I put this in:
```js
          // only log the error once
          if (!error.reactotronWasHere) prettyLogSagaError(error)
          error.reactotronWasHere = true
```

Low tech, sure.  It works though.

**Comment by skellock** [comment]
So your code works great.  

I'm thinking we don't pass the RN error functions into saga though.  I think on slack you'd mentioned putting another [function on Reactotron](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-react-native/src/plugins/track-global-errors.js#L71) called `reportError` or something.

Then in our monitor, we just call `Reactotron.reportError && Reactotron.reportError(error)`.

`reportError` is essentially just `prettyLogSagaError()` relocated.  =)

And now we have a way to also report errors needed for #276 .

This'll be the first time two plugins "talk" to each other, but I'm 100% down with that.

**Comment by rmevans9** [comment]
Nice! I was starting to move in that direction and starting to see if the same error object is passed to each of the promises... I see that is the case! Very nice.

**Comment by skellock** [comment]
Ya.  You kinda nailed it here dude.  Great work.

**Comment by rmevans9** [comment]
Yeah, I think moving that logic works. I will work on moving that around. When we setup Reactotron we will need to still pass in those internal RN functions because I still have not found a way to pull them from within the plugin itself. But wrapping the use of them into a more generic method on the Reactotron object I think would be fantastic.

**Comment by skellock** [comment]
Two things I learned here:

* It fires in triplicate because Root Saga -> takeLatest -> Our Running Saga.  That's 3 tasks.  So it pops up the tree rejecting the promises along the way.

* This doesn't catch `put` effects.  And apparently that's on their radar (https://github.com/yelouafi/redux-saga/issues/632).  Apparently `put.sync` (called `put.resolve` next build) is a thing.  I had no idea.  I had thought it was sync (which now makes a tonne of things more clear!)

Since our goal is just monitoring (not control flow), it might be worth seeing of `put`-bombs show up in a few other places:

* the logger on `createSagaMiddleware`
* the `onError` on `createSagaMiddleware`
* or; even some caveman wrapper implementation of `runSaga(_, { dispatch: ... })`

Just spitballing of course.

I find in my journeys, a make many errors on the React components caused by `PUT`s.  I'd love to have that visibility too.

**Comment by rmevans9** [comment]
I am sure one of those options will log put failures. I'll get an example setup and test later today.

**Comment by rmevans9** [comment]
Rearranged code to make this more solid. This still doesn't handle `puts`. That is next on my list. Updated the demo app to show off the neat features

**Pull request merged**
