### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by jsynowiec**
Reorganized download/installation section, added instruction on installing via Homebrew.

Should be merged after https://github.com/caskroom/homebrew-cask/pull/24012 is accepted and merged.

### CODE REVIEW

**Comment by skellock** [comment]
Thanks.  I see that the linked PR on homebrew-cask was closed but not merged.

**Comment by jsynowiec** [comment]
By mistake I've deleted my remote branch. It's now open.

**Comment by jsynowiec** [comment]
Linked PR is now merged.

**Comment by skellock** [comment]
Thanks.  The readme was changed, so we'll need this rebased. Thanks for all your work coordinating this.  Cask looks like something I would use!

**Pull request merged**
